### ISSUE TITLE
Tome Rater (PWP)

### ISSUE THREAD

**Issue by asadmehdi785** [driskerr/PWP#1]
**Note:** Since exactly one capstone project was required for submission, I will only be grading this project. If you would like feedback on your other project, then you can reach out to your peers on Slack.

### Criteria 1: Valid Python Code
* _Score Level:_ 1
* _Comment(s):_ Code runs with errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4
* _Comment(s):_ Code produces the suite of functions and classes required of it and calls them in an appropriate order.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes.
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4
* _Comment(s):_ Code uses language features appropriately. If a task can be solved with a Python language feature, it is.
 
### Overall Score: 13/16
Overall, excellent work with this project! You did a good job implementing the required methods for the project, while using Python language features appropriately to help you. Well done with that.

Unfortunately, I wasn't able to get your code running the way it was submitted. I initially tested your code using the tests you wrote yourself on the bottom of the file, but I got this error:

```
Traceback (most recent call last):
  File "TomeRater.py", line 355, in <module>
    TR.get_n_most_expensive_books(1)
  File "TomeRater.py", line 215, in get_n_most_expensive_books
    most_expensive_list.append(book)
NameError: name 'most_expensive_list' is not defined
```

This was probably due to a mistake on line 212 here:

https://github.com/driskerr/PWP/blob/0ccde751f83dbfb4d90d68ca09df59362e9be5c6/1_TomeRater/TomeRater.py#L210-L216

I think you meant for that to be `most_expensive_list`.

After that, I tested your code using the `populate.py` file which came with the project. Unfortunately, I got another error with that:

```
Traceback (most recent call last):
  File "populate.py", line 42, in <module>
    print(Tome_Rater.get_most_read_book())
AttributeError: 'TomeRater' object has no attribute 'get_most_read_book'
```

However, that was probably just because you named that attribute `most_read_book` instead of `get_most_read_book`, so after I changed how it was called then the tests ran correctly.

Without those errors, you would have received full points on this project, as you did an excellent job otherwise. I especially liked how you went above and beyond with the extra methods which weren't part of the original requirements.

Good work overall. I hope you enjoyed the course!

**Comment by driskerr** [comment]
Hi Asad! Thanks for the feedback! You were very thorough.

You're right I did make a silly typo with the `get_n_most_expensive_book()` function.

However, I think there is a discrepancy in the instructions and the test code for `most_read_book`/ `get_most_read_book`. 

The instructions for this project ask us to create a function `most_read_book` on page 8.
> `most_read_book` , which should iterate through all of the books in `self.books` and return the book that has been read the most.
> Remember that the keys of `self.books` are Books, and the values are how many times they’ve been read.

But the test code, "populate.py", calls a `get_most_read_book` function. 


While I'm at it, I also noted another discrepancy between the instructions and test code for the arguments of `add_user()`. When creating the optional list of books, the instructions asks us to save this list to the variable "books" on page 8, however in the test code (populate.py) this list referred to as "user_books" in line 19.


Going forward, it would be helpful to fellow learners if the instructions and test code reinfornce one another!
